### ISSUE TITLE
Request development guidelines

### ISSUE THREAD

**Issue by bhswallow** [OP-TEE/build#609]
Hello, bosses! 
I would like to have a development board (or virtual machine) that can port op-tee and write my own TA and CA in it, and this development board (or virtual machine) can install Android OS, I also need to install my own apk in this Android OS (with UI), This allows the apk to call the ca through jni and, ultimately, the ta. What should I do?

I wish I could find such a development board or virtual machine

**Comment by jbech-linaro** [comment]
**Virtual machines**
Android is what makes this challenging. Without it, you could simply use our [QEMU v8 setup](https://optee.readthedocs.io/en/latest/building/devices/qemu.html#qemu-v8). Our QEMU setups are more than capable to implement, run and debug both CA's as well as TA's. But for virtualized Android environments, I believe you're out of luck.

**Development board**
We used to maintain [AOSP builds for OP-TEE](https://optee.readthedocs.io/en/latest/building/aosp/aosp.html) for the old HiKey 620 and 960 devices (no longer possible to purchase). However, due to less interest and lack of time from a maintainers point-of-view we haven't updated that in quite some time, so it's very likely that it won't work if you try the latest. However, an older tagged build should still work.

The best way to transfer TA's, CA's, host libraries, etc. to an Android device, in my view, is to use the command ``adb push`` after the Android environment is up and running.
