### ISSUE TITLE
Unavaliabilty of optee_client_java_api. 

### ISSUE THREAD

**Issue by AmolProjects** [OP-TEE/build#629]
I want to integrate OP-TEE client in Android studio. So i need optee_client java_api. I go through the following links but didnt get api
 https://github.com/OP-TEE/optee_client_java_api.
 https://github.com/linaro-swg/optee_client_java_api 
 They are showing 404 error.
 I also tried implementing dependencies in android gradel file but no use
 implementation 'com.github.OP-TEE.optee_client:optee_client_java_api:3.14.0'
 So please provide proper link so i will get optee_client_java_api

**Comment by jbech-linaro** [comment]
Pardon my ignorance. I've been involved in this project since the start and I cannot recall hearing about these gits ever. So, from an official OP-TEE point of view, this is nothing we've ever worked with nor supported. Having said that, since OP-TEE is open source it could very well be that someone else has done work elsewhere, but that is not something that we're aware of.

**Comment by AmolProjects** [comment]
I got this link from Chat Gpt. I just asked how to integrate op-tee in android studio he suggested me this links. Is there any way other than this to integrate optee client in android studio?

**Comment by jbech-linaro** [comment]
Alright, today we all learned something! 😁

**Comment by jenswi-linaro** [comment]
I asked ChatGPT the same and got this good advice at the end:
_Note that integrating OP-TEE in Android Studio is a complex process and requires a good understanding of both OP-TEE and Android development. It is recommended that you read the OP-TEE documentation thoroughly and have a good understanding of the Android NDK (Native Development Kit) before attempting this integration._
